#!/bin/bash
set -eu

if ! which tailwindcss > /dev/null; then
  echo "This script needs Tailwind installed." >&2
  echo "Run 'npm install -g tailwindcss' and try again." >&2
  exit 1
fi

cd $(dirname $0)

tailwindcss build styles.css -o ../static/css/generated.css
