#!/bin/bash
set -eu
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir

# Install the dependencies at the versions indicated by package.json and package-lock.json
npm install

npx tailwindcss build styles.css -o ../static/css/generated.css
npx minify ../static/css/generated.css > ../static/css/generated.css.min
mv ../static/css/generated.css{.min,}
