# Using a Merge queue makes Mergify automatically keep the PR
# up-to-date with 'main', one PR at a time.
queue_rules:
  - name: default_queue
    conditions:
        - "check-success=build"
    merge_method: squash
    commit_message_template: |-
      {{ title }} (#{{number}})
      {{ body }}
      {# Add co-author information at the end of the squash merge commit message #}
      {% for co_author in co_authors | unique -%}
      Co-Authored-By: {{ co_author.name }} <{{ co_author.email }}>
      {% endfor -%}
      {# `Co-Authored-By` lines must the be last ones for GitHub to recognize them #}

pull_request_rules:
  - name: Automatic squash merge on approval
    conditions:
        - and:
          - "#approved-reviews-by>=1"
          - "#changes-requested-reviews-by=0"
          - "check-success=build"
          - "check-success=cypress"
    actions:
      comment:
        message: Thank you for contributing! Your pull request is now going on the merge train (choo choo! Do not click update from main anymore, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: default_queue
merge_queue:
  max_parallel_checks: 1
