#!/bin/bash
# Helper script to run e2e tests against a local test instance
set -eu
scriptdir=$(cd $(dirname $0) && pwd)

# This is expected to run from the repo root
cd $scriptdir/..

pids=""
trap 'kill $pids' EXIT

export PORT=5050
env HEROKU_APP_NAME=localhost SECRET_KEY=TheSecret python app.py 2>&1 | tee e2e-server.log &
pids="$pids $!"

endpoint=http://localhost:$PORT

# We need to wait a bit for the server to come up. curl for a max time
up=false
for i in $(seq 0 100); do
  http_code=$(curl -sSf -o /tmp/result.txt -w '%{http_code}' "$endpoint" || true)

	if [[ "$http_code" -eq 200 ]]; then
    up=true
		break
	fi
done

if ! $up; then
  echo "Server didn't start in time..." >&2
  exit 1
fi

# Finally!
python e2e_tests.py --endpoint http://localhost:$PORT
