#!/bin/bash
set -eu
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir

# Install NPM-based tools we need
npm ci --silent

# Validate adventure files against their schema
#
# The error messages produced by pajv are pretty bad, but we will just
# say that getting an error is better than getting NO error.
#
# If we ever care enough to do something about this, we should be interpreting
# the JSON error outputs of this tool and re-interpreting them with useful
# error messages.
cd ../coursedata/adventures/
$scriptdir/node_modules/.bin/pajv validate \
    --errors=text \
    -s "adventures.schema.json" \
    -d "*.yaml"

cd ../level-defaults/
$scriptdir/node_modules/.bin/pajv validate \
    --errors=text \
    -s "levels.schema.json" \
    -d "*.yaml"

node $scriptdir/validate-texts.js $scriptdir
