start: program
program: ask _EOL
_EOL: "\r"?"\n"

// Felienne dd 15 maart 2021
// problem is when strings can be unquated, anything can be parsed as a text
// we solve this by finally fixing the ask problem
// not sure if there are other issues, lets see!

ask : var " is ask " QTEXT*

var: NAME -> var
QTEXT: "'" /([^\n,]+)/ "'" //anything can be parsed except for a newline and a comma for list separators



%import common.CNAME -> NAME

