command: print | ifs elses? | ask | for_loop | assign_list | list_access_var | assign

//new for level 8, for loop and the end-blocks
for_loop: "for " (NAME | var) " in " "range " (NUMBER | var) " to " (NUMBER | var) (" step " (NUMBER | var))? _EOL (" "+ command) (_EOL " "+ command)* _EOL "end-block"

elses: _EOL (" ")* "else" _EOL (" "+ command) (_EOL " "+ command)* _EOL "end-block"
ifs: "if " condition _EOL (" "+ command) (_EOL " "+ command)* _EOL "end-block" //'if' cannot be used in Python, hence the name of the rule is 'ifs'
