// from this level on, we allow nesting
// so we only need to remove error commands in repeat

command: -= error_repeat_no_print | error_repeat_no_times

//  adds and and or

ifs: _IF _conditions _EOL (_SPACE command) (_EOL _SPACE command)* _EOL? _END_BLOCK //'if' cannot be used in Python, hence the name of the rule is 'ifs'
_conditions: condition | and_condition | or_condition

and_condition: (condition) (_AND condition)*
or_condition: (condition) (_OR condition)*
