// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeKeyword, extendKeyword} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "+pQYQPOOOOQO'#DO'#DOQYQPOOOzQPO'#DRO!YQPO'#C}OOQO'#DW'#DWO!eQPO'#CtOOQO'#DY'#DYO!mQPO'#CuOOQO'#DZ'#DZO!uQPO'#CwOOQO'#D['#D[O!}QPO'#CxOOQO'#D]'#D]O#VQPO'#CyOOQO'#Cv'#CvOOQO'#D^'#D^O#_QPO'#CzOOQO'#D_'#D_O#mQPO'#C{OOQO'#Da'#DaO#uQPO'#C|OOQO'#Cm'#CmQuQPO'#DPQ#}QPOOOOQO-E6|-E6|OOQO'#DQ'#DQO$lQPO,59YOOQO'#DR'#DROOQO-E7P-E7PO$wQPO'#DXOOQO-E7U-E7UOOQO'#DX'#DXO%VQPO,59`O%bQPO,59aOOQO-E7W-E7WO%mQPO,59cOOQO-E7X-E7XOOQO,59c,59cO%xQPO,59dOOQO-E7Y-E7YOOQO,59d,59dO&TQPO,59eOOQO-E7Z-E7ZOOQO,59e,59eO&`QPO,59fOOQO-E7[-E7[OOQO,59f,59fO&kQPO,59gOOQO-E7]-E7]O&sQPO,59hOOQO-E7_-E7_O&{QPO,59kOOQO-E6}-E6}OOQO-E7O-E7OO'pQPO'#DRO(RQPO1G.tOOQO1G.t1G.tOOQO'#DV'#DVO(aQPO1G.yOOQO'#DS'#DSO(iQPO,59[OOQO-E7V-E7VOOQO'#D`'#D`O(tQPO1G/ROOQO'#Db'#DbO(|QPO1G/SO!pQPO'#DUO)UQPO7+$cO)aQPO7+$eOOQO-E7T-E7TOOQO-E7Q-E7QOOQO'#DT'#DTO)lQPO1G.vOOQO1G.v1G.vOOQO-E7^-E7^OOQO7+$m7+$mOOQO-E7`-E7`OOQO7+$n7+$nO)zQPO,59pOOQO-E7S-E7SOOQO-E7R-E7R",
  stateData: "*Y~O_OS!XOS~OSTOTXOUZOV]OW`OXVOZbO]dOcRO!YPO~OYjOcuX!VuX!YuX~OclO!VqX!YqX~OSTOcnO~OXVOclO~OTXOctO~OUZOcwO~OV]OczO~OW`Oc}O!VnX!YnX~OZbOclO~O]dOclO~OSTOTXOUZOV]OW`OXVOZbO]dOcRO~OP![OYjOc!XO~OQ!^Oc{X!V{X!Y{X~OcnO!Vha!Yha~OclO!Via!Yia~OQ!^O!Vka!Yka~OQ!^O!Vla!Yla~OQ!^O!Vma!Yma~OQ!^O!Vna!Yna~O^!aOclO~O[!cOclO~O!YPOSsaTsaUsaVsaWsaXsaZsa]sacsa!Vsa~OQ!^OcuXfuX!VuX!YuX~OclOf!eO!Vbi!Ybi~OP![OclO~OQ!^OR!jOc!lO~O^!aOc!nO~O[!cOc!pO~Of!eO!Veq!Yeq~OclO!Vgq!Ygq~OR!jOcdi!Vdi!Ydi~OclOfxa!Vxa!Yxa~O",
  goto: "&h!VPPPPPPPPPPPPPPPPP!W!]P!b!]P!]!]!]!]!u!u!u!]!]!]!]!z#U#]#c$T$`$f$l$r$z%Q%Y%b%j%r%z&S&Y&bVgOQhVfOQhSpUqQvYQy[Q|^Q!PaR!ZkV_OQhQQOSiQ!UR!UgShOQR!VhQkRR!WkUSOQh^mSr!Q!S!Y!g!qQrWQ!QcQ!SeQ!YkQ!g!]R!q!e[!_ntwz}!XR!i!_Q!k!_R!s!kQ!f!YR!r!fQ!]kR!h!]UUOQhRoUQqUR!`qUWOQhRsWUYOQhRuYU[OQhRx[U^OQhR{^UaOQhR!OaUcOQhR!RcQ!b!QR!m!bUeOQhR!TeQ!d!SR!o!d",
  nodeNames: "⚠ ask at random print forward turn color sleep play is add from remove toList Comment Program Command Assign Text ListAccess AssignList Comma Ask Print Play Turtle Forward Turn Color Sleep Add Remove ErrorInvalid",
  maxTerm: 56,
  nodeProps: [
    ["group", 26,"turtle"]
  ],
  skippedNodes: [0,15],
  repeatNodeCount: 19,
  tokenData: "$P~RbOY!ZYZ#XZp!Zpq#^qs!Zst#ct|!Z|}#z}#Q!Z#RBn!ZBnBo#zBo&FV!Z&FV&FW#z&FW;'S!Z;'S;=`#R<%l?Hb!Z?Hb?Hc#z?HcO!Z~!`Zc~OY!ZZp!Zqs!Zt|!Z}#Q!Z#RBn!ZBo&FV!Z&FW;'S!Z;'S;=`#R<%l?Hb!Z?HcO!Z~#UP;=`<%l!Z~#^O!Y~~#cO!X~~#hS_~OY#cZ;'S#c;'S;=`#t<%lO#c~#wP;=`<%l#c~$POf~",
  tokenizers: [0],
  topRules: {"Program":[0,16]},
  dynamicPrecedences: {"33":-10},
  specialized: [{term: 19, get: (value: any, stack: any) => (specializeKeyword(value, stack) << 1), external: specializeKeyword},{term: 19, get: (value: any, stack: any) => (extendKeyword(value, stack) << 1) | 1, external: extendKeyword, extend: true}],
  tokenPrec: 0
})
