// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
import {specializeKeyword, extendKeyword} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "-tQYQPOOOOQO'#DR'#DRQYQPOOO}QPO'#DUO!]QPO'#DQOOQO'#D^'#D^O!hQPO'#CvOOQO'#D_'#D_O!sQPO'#CwOOQO'#D`'#D`O#RQPO'#CxOOQO'#Da'#DaO#ZQPO'#CzOOQO'#Db'#DbO#cQPO'#C{OOQO'#Dc'#DcO#kQPO'#C|OOQO'#Cy'#CyOOQO'#Dd'#DdO#sQPO'#C}OOQO'#De'#DeO$RQPO'#DOOOQO'#Dg'#DgO$ZQPO'#DPOOQO'#Cn'#CnQxQPO'#DSQ$cQPOOOOQO-E7P-E7POOQO'#DT'#DTO%TQPO,59ZOOQO'#DU'#DUOOQO-E7S-E7SOOQO-E7[-E7[O%`QPO'#DZO%tOSO'#DmO%|OQO'#DqOOQO'#Cu'#CuOOQO'#DZ'#DZO&UQPO,59cOOQO-E7]-E7]O&gQPO,59dOOQO-E7^-E7^O&rQPO,59fOOQO-E7_-E7_OOQO,59f,59fO&}QPO,59gOOQO-E7`-E7`OOQO,59g,59gO'YQPO,59hOOQO-E7a-E7aOOQO,59h,59hO'eQPO,59iOOQO-E7b-E7bOOQO,59i,59iOOQO-E7c-E7cO'pQPO,59jOOQO-E7e-E7eO'uQPO,59kO'zQPO,59nOOQO-E7Q-E7QOOQO-E7R-E7RO(rQPO'#DUO)TQPO1G.uOOQO1G.u1G.uOOQO'#DY'#DYO)cQPO1G.zOOQO'#DV'#DVO)qQPO,59]OOOO'#D['#D[O)|OSO,5:XOOQO,5:X,5:XOOOO'#D]'#D]O*UOQO,5:]OOQO,5:],5:]OOQO-E7X-E7XOOQO'#Df'#DfO*^QPO1G/UOOQO'#Dh'#DhO*fQPO1G/VO#UQPO'#DXO*nQPO7+$dOOQO-E7W-E7WO*yQPO7+$fOOQO-E7T-E7TOOQO'#DW'#DWO+[QPO1G.wOOQO1G.w1G.wOOOO-E7Y-E7YOOQO1G/s1G/sOOOO-E7Z-E7ZOOQO1G/w1G/wOOQO-E7d-E7dOOQO7+$p7+$pOOQO-E7f-E7fOOQO7+$q7+$qO+pQPO,59sOOQO-E7V-E7VOOQO-E7U-E7U",
  stateData: ",O~O`OS!_OS~OSVOTZOU]OV_OWbOXXOZdO]fO_TOdRO!`PO~OYlOdxX!]xX!`xX~OdnO!]tX!`tX~O_TO!]jX!`jX~OSVOdqO!brO!fsO~OXXOdnO~OTZOdzO~OU]Od}O~OV_Od!QO~OWbOd!TO!]qX!`qX~OZdOd!XO~O]fOd!ZO~OSVOTZOU]OV_OWbOXXOZdO]fO_TOdRO~OP!bOYlOd!_O~OQ!dOd}X!]}X!`}X!b}X!f}X~O!c!fO!d!hO~O!g!iO!h!kO~OdqO!brO!fsO!]ka!`ka~OdnO!]la!`la~OQ!dO!]na!`na~OQ!dO!]oa!`oa~OQ!dO!]pa!`pa~OQ!dO!]qa!`qa~O^!mO~O[!oO~O!`POSvaTvaUvaVvaWvaXvaZva]va_vadva!]va~OQ!dOdxXgxX!]xX!`xX~OdnOg!qO!]ci!`ci~OP!bOdqO!brO!fsO~OQ!dOR!vOd!xO~O!c!fO!d!zO~O!g!iO!h!|O~O^!mOd#OO~O[!oOd#QO~Og!qO!]fq!`fq~OdqO!brO!fsO!]hq!`hq~OR!vOdei!]ei!`ei!bei!fei~OdnOg{a!]{a!`{a~O",
  goto: "'c!fPPPPPPPPPPPPPPPPPP!g!lP!q!lP!l#W!l!l!l!l#^#^#^!l!l!l!l#c#m#t#z$`$k$q$w$}%X%_%e%m%u%}&V&_&g&o&w&}'VPPPP']PPP']ViOQjVhOQjWuWv!c!tQ|[Q!P^Q!S`Q!VcR!amXuWv!c!tVaOQjQQOSkQ![R![iSjOQR!]jQmRR!^mUSOQjWoSx!`#RQxYQ!`mR#R!q[!eqz}!Q!T!_R!u!eQ!w!eR#T!wQ!r!`R#S!rQ!cmR!s!cQvWS!lv!tR!t!cQ!grR!y!gQ!jsR!{!jUUOQjRpUUWOQjRwWUYOQjRyYU[OQjR{[U^OQjR!O^U`OQjR!R`UcOQjR!UcUeOQjR!WeQ!n!XR!}!nUgOQjR!YgQ!p!ZR#P!pXtWv!c!t",
  nodeNames: "⚠ ask at random print forward turn color sleep play is add from remove toList clear Comment Program Command Assign Text ListAccess AssignList Comma Ask String Clear Print Play Turtle Forward Turn Color Sleep Add Remove ErrorInvalid",
  maxTerm: 70,
  nodeProps: [
    ["group", 29,"turtle"]
  ],
  skippedNodes: [0,16],
  repeatNodeCount: 22,
  tokenData: "$g~ReOY!dYZ#eZp!dpq#jqr!drs#ost#ttw!dwx$]x|!d|}$b}#Q!d#RBn!dBnBo$bBo&FV!d&FV&FW$b&FW;'S!d;'S;=`#_<%l?Hb!d?Hb?Hc$b?HcO!d~!i[d~OY!dZp!dqr!dtw!dx|!d}#Q!d#RBn!dBo&FV!d&FW;'S!d;'S;=`#_<%l?Hb!d?HcO!d~#bP;=`<%l!d~#jO!`~~#oO!_~~#tO!b~~#yS`~OY#tZ;'S#t;'S;=`$V<%lO#t~$YP;=`<%l#t~$bO!f~~$gOg~",
  tokenizers: [2, new LocalTokenGroup("_~RQYZXwxX~^O!h~~", 14, 69), new LocalTokenGroup("_~RQYZXrsX~^O!d~~", 14, 65)],
  topRules: {"Program":[0,17]},
  dynamicPrecedences: {"36":-10},
  specialized: [{term: 20, get: (value: any, stack: any) => (specializeKeyword(value, stack) << 1), external: specializeKeyword},{term: 20, get: (value: any, stack: any) => (extendKeyword(value, stack) << 1) | 1, external: extendKeyword, extend: true}],
  tokenPrec: 0
})
