// This file was generated by lezer-generator. You probably shouldn't edit it.
// (It was then subsequently modified by generate-lezer-parsers).
import {LRParser} from "@lezer/lr"
import {specializeKeywordGen, extendKeywordGen} from "./tokens"
export function generateParser(level: number, language: string): LRParser {
  const specializeKeyword = specializeKeywordGen(level, language);
  const extendKeyword = extendKeywordGen(level, language);
  return LRParser.deserialize({
  version: 14,
  states: "2rQYQPOOOOQO'#Dg'#DgQYQPOOO!WQPO'#DjO!lQPO'#DdOOQO'#Dp'#DpO!zQPO'#C}O#YQPO'#DOOOQO'#Dq'#DqO#bQPO'#DPOOQO'#Dr'#DrO#jQPO'#DROOQO'#Ds'#DsO#rQPO'#DSOOQO'#Dt'#DtO#zQPO'#DTOOQO'#DQ'#DQOOQO'#Du'#DuO$SQPO'#DUOOQO'#Dv'#DvO$eQPO'#DVOOQO'#Dx'#DxO$mQPO'#DWOOQO'#Dz'#DzO$uQPO'#DXOOQO'#EO'#EOO%rQPO'#DeOOQO'#EP'#EPO%yQPO'#DfOOQO'#Ct'#CtQ!RQPO'#DhQ&RQPOOOOQO-E7e-E7eOOQO'#Di'#DiO&]QPO,59aOOQO'#Cw'#CwO&hQPO,59aOOQO'#Dj'#DjOOQO-E7h-E7hOOQO-E7n-E7nO&pQPO'#DoOOQO'#Do'#DoO'UQPO,59jO'gQPO'#DjO(UQPO,59kOOQO-E7o-E7oOOQO,59k,59kO(dQPO,59mOOQO-E7p-E7pOOQO,59m,59mO(rQPO,59nOOQO-E7q-E7qOOQO,59n,59nO)QQPO,59oOOQO-E7r-E7rOOQO,59o,59oO)`QPO,59pOOQO-E7s-E7sOOQO,59p,59pO)nQPO,59qOOQO-E7t-E7tO)vQPO,59rOOQO-E7v-E7vOOQO-E7x-E7xO*OQPO'#DZOOQO'#DY'#DYOcQPO,59sOcQPO,5:POOQO'#Dc'#DcOOQO-E7|-E7|OOQO,5:P,5:POOQO-E7}-E7}OcQPO,5:QO*gQPO,5:SOOQO-E7f-E7fOOQO-E7g-E7gO+hQPO1G.{OOQO1G.{1G.{OOQO'#Dn'#DnO,SQPO1G/RO,_QPO1G.{OOQO'#Dk'#DkO,mQPO,59dOOQO-E7m-E7mOOQO'#Dw'#DwO,xQPO1G/]OOQO'#Dy'#DyO-QQPO1G/^O-YQPO,59uO-`QPO,59vOOQO'#D^'#D^O-hQPO,59wO-pQPO'#D`O-{QPO,59yOOQO'#D|'#D|O.TQPO,59{OOQO'#D}'#D}O.]QPO,59|OcQPO1G/_O.eQPO1G/_OOQO1G/k1G/kOcQPO1G/lO.pQPO1G/lOOQO'#Cz'#CzO$hQPO'#DmO.{QPO7+$kOOQO-E7l-E7lO/dQPO7+$mOOQO-E7i-E7iOOQO'#Dl'#DlO/uQPO1G/OOOQO1G/O1G/OOOQO-E7u-E7uOOQO7+$w7+$wOOQO-E7w-E7wOOQO7+$x7+$xOOQO'#D{'#D{O0ZQPO1G/aOOQO1G/b1G/bOOQO1G/c1G/cOOQO,59z,59zOOQO1G/e1G/eOOQO-E7z-E7zOOQO1G/g1G/gOOQO-E7{-E7{OOQO1G/h1G/hO1RQPO7+$yOOQO7+$y7+$yO1^QPO7+%WOOQO7+%W7+%WO1iQPO,5:XOOQO-E7k-E7kOOQO-E7j-E7jOOQO-E7y-E7yOOQO<<He<<HeOOQO<<Hr<<Hr",
  stateData: "2T~OfOS!vOS~OSgOTiOVkOWVOXYOY[OZ^O[aO]WO_cOaeOcTOjRO!wPO~O^qO!xsOj!^X!t!^X!w!^XT!^X~OjuO!t!WX!w!WXT!WX~OcTO!tqX!wqXTqX~OjxOpyO~O]WOj{O~OXYOj!PO~OY[Oj!SO~OZ^Oj!VO~O[aOj!YO!txX!wxXTxX~O_cOjuO~OaeOjuO~OSgOj!bO~OTiOWVOXYOY[OZ^O[aO]WO_cOaeOcTOjRO~O!wPO~P$}OVkOj!bO~OSgOVkO~P$}OP!pO^qOj{O~OP!pOj{O~OQ!sOj!cXp!cX!t!cX!w!cXT!cX~OjxOpyO!tra!wraTra~OQ!sOj!^X!t!^X!w!^X!y!^X!z!^X!{!^X!|!^XT!^X~OjuO!tsa!wsaTsa~OQ!sO!tua!wuaTua~OQ!sO!tva!wvaTva~OQ!sO!twa!wwaTwa~OQ!sO!txa!wxaTxa~Ob!vOjuO~O`!xOjuO~O^qOd#QOe#SO!xsO!}!|O#O#OO#P#OO~O!wPOS![aT![aV![aW![aX![aY![aZ![a[![a]![a_![aa![ac![aj![a!t![a~OjuO!y#ZO!z#ZO!{#ZO!|#ZO!tii!wiiTii~OP!pOjxOpyO~OjuO!tii!wiiTii~OQ!sOR#aOj#cO~Ob!vOj#eO~O`!xOj#gO~OU#hO^qOj#jOp#jO~Oj#kOp#kO~O!x#lOj!SXp!SX~Oj#mOp#mO~Od#QOj#oO~Oe#SOj#qO~OTiO!t{i!w{i~OTiO!t!Yi!w!Yi~O!y#ZO!z#ZO!{#ZO!|#ZO!tmq!wmqTmq~OjxOpyO!toq!woqToq~OR#aOjlipli!tli!wliTli~OU#hOW}iX}iY}iZ}i[}i]}i_}ia}ic}ij}i!w}i~OTiO!t{q!w{q~OTiO!t!Yq!w!Yq~OjuO!t!aa!w!aa!y!aa!z!aa!{!aa!|!aaT!aa~O",
  goto: "+n!tPPPPPPPPPPPPPPPPPPPPPPPP!u!zP#X#_!z#x!zP!z!z!z!z#|#|#|!z!z!z$X$^$d$d$d$h$d$k$d$d$n!z%Q$X%c%y&Q&['S'_'e'k'r'|([(j(x)W)f)t*S*Y*h*n*v*|+S+Y+fVnOQoUmOQo]!fj!d!e!j#U#XQtRR!{!bWyVz!q#_Q!OXQ!RZQ!U]Q!X_Q![bT!ortT#[!n#]c`OQjo!d!e!j#U#XVmOQoQ!dhR!jlT!chlR!}!bR#P!bQ!hjQ#V!dQ#W!eQ#Y!jQ#r#UR#t#XUmOQoQ#s#VQ#u#YQ#z#rR#{#tQQOYpQ!e!k#U#XQ!ejQ!knQ#U!dR#X!jSoOQR!loQrRS!mr!zR!z!bbSOQjo!d!e!j#U#X^vS|!]!_!n!r#vQ|XQ!]dQ!_fQ!nrQ!rtR#v#[[!tx{!P!S!V!YR#`!tQ#b!tR#x#bQ#]!nR#w#]S!qrtR#^!qQzVS!uz#_R#_!qbUOQjo!d!e!j#U#XRwUbXOQjo!d!e!j#U#XR}XbZOQjo!d!e!j#U#XR!QZb]OQjo!d!e!j#U#XR!T]b_OQjo!d!e!j#U#XR!W_bbOQjo!d!e!j#U#XR!ZbbdOQjo!d!e!j#U#XR!^dQ!w!]R#d!wbfOQjo!d!e!j#U#XR!`fQ!y!_R#f!yUhOQoR!ahQ#i!zR#y#iQ#R!bR#n#RQ#T!bR#p#T^jOQo#V#Y#r#tR!gjUlOQoR!il",
  nodeNames: "⚠ ask at random if else pressed elif print forward turn color sleep play is add from remove to_list clear in not_in Comment Program Command Assign Text Op ListAccess AssignList Op Ask String Clear Print Play Turtle Forward Turn Color Sleep Add Remove If Condition PressedCheck EqualityCheck NotEqualCheck Op ComparisonCheck Op InListCheck NotInListCheck IfLessCommand ErrorInvalid Else Elif",
  maxTerm: 93,
  nodeProps: [
    ["group", 36,"turtle"]
  ],
  skippedNodes: [0,22],
  repeatNodeCount: 25,
  tokenData: ")e~R}YZ$Opq$Tqr$Yrs$est%Ytu%quv%qvw%qwx(Qxy%qyz%qz{%q{|%q|}(p}!O%q!O!P%q!P!Q%q!Q![%q![!]%q!]!^%q!^!_(u!_!`(z!`!a)P!a!b%q!b!c%q!c!}%q!}#O%q#O#P%q#P#Q%q#Q#R%q#R#S%q#S#T%q#T#o%q#o#p%q#q#r%q#r#s%q$gBn%qBnBo)UBo&FV%q&FV&FW)Z&FW;'S%q;'S;=`'z<%l?Hb%q?Hb?Hc)`?HcO%q~$TO!w~~$YO!v~~$]P!_!`$`~$eO!}~~$hVOY$eZr$ers$}s#O$e#P;'S$e;'S;=`%S<%lO$e~%SOp~~%VP;=`<%l$e~%_Sf~OY%YZ;'S%Y;'S;=`%k<%lO%Y~%nP;=`<%l%Y~%vpj~tu%quv%qvw%qxy%qyz%qz{%q{|%q}!O%q!O!P%q!P!Q%q!Q![%q![!]%q!]!^%q!a!b%q!b!c%q!c!}%q!}#O%q#O#P%q#P#Q%q#Q#R%q#R#S%q#S#T%q#T#o%q#o#p%q#q#r%q#r#s%q$gBn%qBo&FV%q&FW;'S%q;'S;=`'z<%l?Hb%q?HcO%q~'}P;=`<%l%q~(TVOY(QZw(Qwx$}x#O(Q#P;'S(Q;'S;=`(j<%lO(Q~(mP;=`<%l(Q~(uO!y~~(zO#P~~)PO!x~~)UO#O~~)ZO!z~~)`O!|~~)eO!{~",
  tokenizers: [0],
  topRules: {"Program":[0,23]},
  dynamicPrecedences: {"54":-10},
  specialized: [{term: 26, get: (value: any, stack: any) => (specializeKeyword(value, stack) << 1), external: specializeKeyword},{term: 26, get: (value: any, stack: any) => (extendKeyword(value, stack) << 1) | 1, external: extendKeyword, extend: true}],
  tokenPrec: 0
})
}
