// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Command = 3,
  Assign = 4,
  Var = 5,
  Name = 6,
  IsToken = 7,
  Text = 8,
  Ask = 9,
  AskToken = 10,
  ErrorInvalid = 11,
  TextWithoutSpaces = 12
