// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_TextWithoutSpaces = {__proto__:null,ask:18, echo:22, forward:28, turn:32, color:36}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lOYQPOOOqQPO'#C`OOQO'#Ch'#ChOvQPO'#CoOOQO'#C_'#C_OOQO'#Cp'#CpQYQPOOO!eQPO'#CcO!jQPO'#CfO!oQPO'#CiO!tQPO'#CkO!yQPO'#CmOOQO,58z,58zOOQO,59Z,59ZOOQO-E6n-E6nOOQO,58},58}OOQO,59Q,59QOOQO,59T,59TOOQO,59V,59VOOQO,59X,59X",
  stateData: "#T~OPOSgOS~OTPOWROXVOZWO^XO`YObZO~OU[O~OU]OTcXWcXXcXZcX^cX`cXbcXecX~OU_O~OU`O~OUaO~OUbO~OUcO~OTWUW~",
  goto: "xePPPfjPPjPPjPjnPnPnPjrTTOUTSOUTQOUQUOR^U",
  nodeNames: "⚠ Comment Program Command Print PrintToken Text Ask TextWithoutSpaces ask Echo echo Turtle Forward forward Turn turn Color color ErrorInvalid",
  maxTerm: 23,
  nodeProps: [
    ["group", 12,"turtle"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "/Q~RaOY!WYZ$^Z]!W]^!z^p!Wpq#iqs!Wst$ct#d!W#d#e$z#eCt!WCtCu)WCuCv!WCvCw,UCw;'S!W;'S;=`$W<%lO!W~!_XW~U~OY!WZ]!W]^!z^p!Wpq#iqs!Wt;'S!W;'S;=`$W<%lO!W~#PUW~OY!zZp!zqs!zt;'S!z;'S;=`#c<%lO!z~#fP;=`<%l!z~#nUU~OY#iZ]#i^s#it;'S#i;'S;=`$Q<%lO#i~$TP;=`<%l#i~$ZP;=`<%l!W~$cOg~~$hSP~OY$cZ;'S$c;'S;=`$t<%lO$c~$wP;=`<%l$c~%RZW~U~OY!WZ]!W]^!z^p!Wpq#iqs!Wt#f!W#f#g%t#g;'S!W;'S;=`$W<%lO!W~%{ZW~U~OY!WZ]!W]^!z^p!Wpq#iqs!Wt#]!W#]#^&n#^;'S!W;'S;=`$W<%lO!W~&uZW~U~OY!WZ]!W]^!z^p!Wpq#iqs!Wt#b!W#b#c'h#c;'S!W;'S;=`$W<%lO!W~'oZW~U~OY!WZ]!W]^!z^p!Wpq#iqs!Wt#h!W#h#i(b#i;'S!W;'S;=`$W<%lO!W~(kXT~W~U~OY!WZ]!W]^!z^p!Wpq#iqs!Wt;'S!W;'S;=`$W<%lO!W~)]YW~OY!zZp!zqs!ztCt!zCtCu)WCuCv!zCvCw){Cw;'S!z;'S;=`#c<%lO!z~*QYW~OY!zZp!zqs!ztCt!zCtCu){CuC|!zC|C}*pC};'S!z;'S;=`#c<%lO!z~*uYW~OY!zZp!zqs!ztCt!zCtCu*pCuCx!zCxCy+eCy;'S!z;'S;=`#c<%lO!z~+lWT~W~OY!zZp!zqs!ztCt!zCtCu+eCu;'S!z;'S;=`#c<%lO!z~,]]W~U~OY!WZ]!W]^!z^p!Wpq#iqs!WtCt!WCtCu,UCuC|!WC|C}-UC};'S!W;'S;=`$W<%lO!W~-]]W~U~OY!WZ]!W]^!z^p!Wpq#iqs!WtCt!WCtCu-UCuCx!WCxCy.UCy;'S!W;'S;=`$W<%lO!W~._ZT~W~U~OY!WZ]!W]^!z^p!Wpq#iqs!WtCt!WCtCu.UCu;'S!W;'S;=`$W<%lO!W",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 8, get: (value: any) => spec_TextWithoutSpaces[value] || -1}],
  tokenPrec: 92
})
