// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
const spec_Text = {__proto__:null,is:13, at:26, random:28, ask:37, clear:45, print:49, forward:55, turn:59, color:63, sleep:67, add:71, to:73, remove:77, from:79, if:83, pressed:89, not:93, in:95, else:102}
export const parser = LRParser.deserialize({
  version: 14,
  states: ",xQYQPOOOOQO'#Db'#DbQYQPOOO!QQPO'#DeO!fQPO'#D_OOQO'#Cu'#CuOOQO'#C_'#C_Q{QPO'#DcQ#fQPOOOOQO'#Cq'#CqO#mQPO'#CsO#xQPO'#CvO#xQPO'#CxO#xQPO'#CzO$QQPO'#C|O$`QPO'#DOO$eQPO'#DRO%XQPO'#D`O%cQPO'#DUOOQO-E7`-E7`OOQO'#Cc'#CcO%kQPO,58zOOQO'#De'#DeOOQO-E7c-E7cO%vQPO,59}OOQO-E7a-E7aO&qQPO'#DgOOQO'#Cd'#CdO(TQPO'#CdO([OQO'#CoOOQO'#Dg'#DgO(dQPO,59_O(xQPO,59bOOQO,59b,59bO)aQPO,59dOOQO,59d,59dO)xQPO,59fOOQO,59f,59fO*aQPO,59hOOQO,59h,59hO*oQPO,59jO*tQPO,59mOOQO'#D^'#D^OOQO,59z,59zOOQO'#DW'#DWO*yQPO'#DXO*|QPO'#DZO+UQPO,59pO+`QPO'#DdO+}QPO1G.qO,UQPO'#CdOOQO'#Dd'#DdO,`QPO1G.fO,qQPO1G.qO#mQPO1G.sOOQO'#Cf'#CfOOQO'#Cg'#CgO,yQPO,5:YO,yQPO,5:YO-RQPO,59SOOOO'#Dh'#DhO-ZOQO,59ZOOQO,59Z,59ZOOQO-E7e-E7eO-cQPO1G/UO-hQPO1G/XO-mQPO,59sO-{QPO,59uO.QQPO,59uOOQO1G/[1G/[O.VQPO1G/[OOQO'#Cl'#ClO.bQPO'#DfO.jQPO7+$]OOQO-E7b-E7bO.xQPO7+$_OOQO1G/t1G/tO/^QPO1G/tOOQO1G.n1G.nOOOO-E7f-E7fOOQO1G.u1G.uOOQO7+$p7+$pOOQO7+$s7+$sOOQO1G/_1G/_OOQO1G/a1G/aO0OQPO1G/aOOQO7+$v7+$vO0TQPO,5:QOOQO,5:Q,5:QOOQO-E7d-E7dOOQO7+${7+${",
  stateData: "0i~OPOS!_OS~OTROfXOhYOkZOm[Oo]Oq^Os_Ov`OybO!TaO!`PO~OUeO!adOT!XX!]!XX!`!XX!T!XX~OTfO!]!RX!`!RX!T!RX~OTROfXOhYOkZOm[Oo]Oq^Os_Ov`O!TaO~OybO~P!tOTlOXkO!hmO~OTlOXkO~OTvO!]pX!`pX!TpX~OTxO~OTyO~OTROfXOhYOkZOm[Oo]Oq^Os_Ov`O~O!]!SX!`!SX~P$jOT}OX!OO~OT!SOX!ROb!WO~O!`POT!Vaf!Vah!Vak!Vam!Vao!Vaq!Vas!Vav!Vay!Va!T!Va!]!Va~O!c!XO!d!XO!e!YO!f!YOT!ZXX!ZX!]!ZX!`!ZX!h!ZX!T!ZX~O]!]OTWXXWX!]WX!`WX!cWX!dWX!eWX!fWX!TWX~O!hWX~P'cOd!`O!i!^O~OTlOXkO!hmO!]ga!`ga!Tga~O!c!XO!d!XO!e!YO!f!YO!]ja!`ja!Tja~O!c!XO!d!XO!e!YO!f!YO!]la!`la!Tla~O!c!XO!d!XO!e!YO!f!YO!]na!`na!Tna~O]!]O!]pa!`pa!Tpa~Ot!bO~Ow!cO~OU!dO!O!fO!P!eO~O!]xa!`xa~P!tO!c!XO!d!XO!e!YO!f!YOT!WXX!WX!]!WX!`!WX!T!WX~O!g!iO~P'fOT!XX!g!XX~P'cOTlOXkO!]Si!`Si!TSi~OTfO!g!iO~OTkOXkO~OT!pO^!pO~Od!rO!i!^O~OT!sO~OT!tO~OT!uOX!uO|!uO!hmO~OT!vO~O!P!wO~O!TaO!]xi!`xi~OTfOX!zO~O!g!iO!]_q!`_q!T_q~OTlOXkO!hmO!]aq!`aq!Taq~O!c!XO!d!XO!e!YO!f!YOT!biX!bi!]!bi!`!bi!h!bi!T!bi~OT!|O~OTfO!]!Ya!`!Ya!g!Ya!T!Ya~OXT~",
  goto: "&z!cPPP!d!iPP!r!uP#`#h#pPP!i$W!iP$]P!iP!iP!i$fP$fP$fP!iP!iPP!iPP$mP$r$uP$uPP$x!i%OP%Z%e%l%r&U&]&gPPPPP&mVVOQWUUOQWTza!PReRWjYo!W!mQpZQr[Qt]S!Qe!UQ!n!ZR!o![]!Zjprt!Q!o]![jprt!Q!oWnYo!W!mQqZQs[Qu]Qw^T!Te!UV!j!R!V!kWnYo!W!mR!u!dZTOQWa!PVUOQWR!PbR|bQ{aR!h!PUUOQWQ!g!PR!x!hQQOScQhRhVSWOQRiWQ!UeR!l!UYSOQWa!PUgS!V!yQ!VeR!y!jS!k!R!VR!{!kQoYS!ao!mR!m!WQ!_mR!q!_gkYZ[]eo!U!W!Z![!m",
  nodeNames: "⚠ Comment Program Command Assign Text is Op Expression Int Op Op ListAccess at random AssignList Comma Ask ask String quote Clear clear Print print Turtle Forward forward Turn turn Color color Sleep sleep Add add to Remove remove from If if Condition EqualityCheck pressed ListCheck not in IfLessCommand ErrorInvalid Else else",
  maxTerm: 71,
  nodeProps: [
    ["group", 25,"turtle"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 7,
  tokenData: "&e~RiOY!pYZ#wZp!ppq#|qs!pst$Rtw!pwx$jxz!pz{$o{|$t|}$y}!O%O!O!P!p!P!Q%T!Q![%Y![!_!p!_!`&`!`#Q!p#RBn!pBo&FV!p&FW;'S!p;'S;=`#q<%l?Hb!p?HcO!p~!u^T~OY!pZp!pqs!ptw!pxz!p!O!P!p!Q!_!p!`#Q!p#RBn!pBo&FV!p&FW;'S!p;'S;=`#q<%l?Hb!p?HcO!p~#tP;=`<%l!p~#|O!`~~$RO!_~~$WSP~OY$RZ;'S$R;'S;=`$d<%lO$R~$gP;=`<%l$R~$oO!h~~$tO!c~~$yO!e~~%OO!g~~%TO!f~~%YO!d~~%a_X~T~OY!pZp!pqs!ptw!pxz!p!O!P!p!Q![%Y![!_!p!`#Q!p#RBn!pBo&FV!p&FW;'S!p;'S;=`#q<%l?Hb!p?HcO!p~&eO!a~",
  tokenizers: [1, new LocalTokenGroup("[~RPwxU~ZOd~~", 11, 71)],
  topRules: {"Program":[0,2]},
  dynamicPrecedences: {"49":-10},
  specialized: [{term: 5, get: (value: any) => spec_Text[value] || -1}],
  tokenPrec: 712
})
