// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Command = 3,
  Assign = 4,
  TextWithoutSpaces = 5,
  Ask = 7,
  Print = 9,
  Turtle = 11,
  Sleep = 18,
  ErrorInvalid = 20
