// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeKeyword} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%vQYQPOOOOQO'#Co'#CoQYQPOOOOQO'#Cq'#CqOtQPO'#CfOOQO'#Cr'#CrO|QPO'#ChOOQO'#Cs'#CsO!UQPO'#CiOOQO'#Ct'#CtO!^QPO'#CkOOQO'#Cu'#CuO!fQPO'#ClOOQO'#Cv'#CvO!nQPO'#CmOOQO'#Cj'#CjOOQO'#Cw'#CwO!vQPO'#CnOOQO'#Ce'#CeQoQPO'#CpQ#RQPOOOOQO-E6m-E6mOOQO-E6o-E6oOOQO,59Q,59QOOQO-E6p-E6pOOQO,59S,59SOOQO-E6q-E6qOOQO,59T,59TOOQO-E6r-E6rOOQO,59V,59VOOQO-E6s-E6sOOQO,59W,59WOOQO-E6t-E6tOOQO,59X,59XOOQO-E6u-E6uO#jQPO,59[OOQO-E6n-E6n",
  stateData: "$X~OVOSnOS~OPROQXORZOSVOTTOU]OZ`OoPO~OPROZgO~OTTOZiO~OSVOZkO~OQXOZmO~ORZOZoO~OU]OZqO~OZ`OlbXobX~OPROQXORZOSVOTTOU]OZ`O~OoPOPdaQdaRdaSdaTdaUdaZdalda~O",
  goto: "#ilPPPPPPPPPmrPrrrwwwr|!W!_!g!o!w#P#X#aVcOQdVbOQdV_OQdQQOSeQsRscSdOQRtdUSOQdRfSUUOQdRhUUWOQdRjWUYOQdRlYU[OQdRn[U^OQdRp^UaOQdRra",
  nodeNames: "⚠ print forward turn echo ask color Comment Program Command Print Text Ask Echo Turtle Forward Turn Color ErrorInvalid",
  maxTerm: 31,
  nodeProps: [
    ["group", 14,"turtle"]
  ],
  skippedNodes: [0,7],
  repeatNodeCount: 9,
  tokenData: "#O~RXOYnYZ!]Zpnpq!bqsnst!gt;'Sn;'S;=`!V<%lOn~sUZ~OYnZpnqsnt;'Sn;'S;=`!V<%lOn~!YP;=`<%ln~!bOo~~!gOn~~!lSV~OY!gZ;'S!g;'S;=`!x<%lO!g~!{P;=`<%l!g",
  tokenizers: [0],
  topRules: {"Program":[0,8]},
  specialized: [{term: 11, get: (value: any, stack: any) => (specializeKeyword(value, stack) << 1), external: specializeKeyword}],
  tokenPrec: 0
})
