// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Command = 3,
  Assign = 4,
  Text = 5,
  ListAccess = 7,
  AssignList = 10,
  Comma = 11,
  Ask = 12,
  Print = 14,
  Turtle = 16,
  Sleep = 23,
  Add = 25,
  Remove = 28,
  ErrorInvalid = 31
