// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeKeyword, extendKeyword} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "0[QYQPOOO!QQPO'#DaO!`QPO'#D]OOQO'#Dg'#DgO!kQPO'#C{OOQO'#Dh'#DhO!vQPO'#C|OOQO'#Di'#DiO#RQPO'#C}OOQO'#Dj'#DjO#ZQPO'#DPOOQO'#Dk'#DkO#cQPO'#DQOOQO'#Dl'#DlO#kQPO'#DROOQO'#DO'#DOOOQO'#Dm'#DmO#sQPO'#DSOOQO'#Dn'#DnO$RQPO'#DTOOQO'#Dp'#DpO$ZQPO'#DUOOQO'#Dr'#DrO$cQPO'#DVOOQO'#Dw'#DwO$kQPO'#D^OOQO'#Cs'#CsO$rQPO'#D_QYQPOOOOQO'#D`'#D`O$wQPO,59`OOQO'#Da'#DaOOQO-E7_-E7_OOQO-E7e-E7eO%SQPO'#DfOOQO'#Df'#DfO%eQPO,59hOOQO-E7f-E7fO%sQPO'#DaO&_QPO,59iOOQO-E7g-E7gOOQO,59i,59iO&jQPO,59kOOQO-E7h-E7hOOQO,59k,59kO&uQPO,59lOOQO-E7i-E7iOOQO,59l,59lO'QQPO,59mOOQO-E7j-E7jOOQO,59m,59mO']QPO,59nOOQO-E7k-E7kOOQO,59n,59nO'hQPO,59oOOQO-E7l-E7lO'pQPO,59pOOQO-E7n-E7nOOQO-E7p-E7pO'xQPO'#DXOOQO'#DW'#DWO(TQPO,59qOOQO'#Dv'#DvO(TQPO,59xOOQO'#D['#D[OOQO-E7u-E7uOOQO,59x,59xOOQO,59y,59yOOQO-E7]-E7]OOQO-E7^-E7^O(xQPO1G.zOOQO1G.z1G.zOOQO'#De'#DeO)aQPO1G/POOQO'#Db'#DbO)lQPO,59bOOQO-E7d-E7dOOQO'#Do'#DoO)wQPO1G/ZOOQO'#Dq'#DqO*PQPO1G/[O*XQPO,59sOOQO'#Dt'#DtO*gQPO,59tOOQO'#Du'#DuO*oQPO,59uO(TQPO1G/]O*wQPO1G/]OOQO-E7t-E7tOOQO1G/d1G/dOOQO'#Cx'#CxO$UQPO'#DdO+PQPO7+$iOOQO-E7c-E7cO+eQPO7+$kOOQO-E7`-E7`OOQO'#Dc'#DcO+sQPO1G.|OOQO1G.|1G.|OOQO-E7m-E7mOOQO7+$u7+$uOOQO-E7o-E7oOOQO7+$v7+$vOOQO'#Ds'#DsO,UQPO1G/_OOQO1G/_1G/_OOQO-E7r-E7rOOQO1G/`1G/`OOQO-E7s-E7sOOQO1G/a1G/aO,|QPO7+$wOOQO7+$w7+$wO-UQPO,5:OOOQO-E7b-E7bOOQO-E7a-E7aOOQO-E7q-E7qOOQO<<Hc<<Hc",
  stateData: "-m~OeOS!nOS~OSfOThOVTOWXOXZOY]OZ`O[VO^bO`dObROiPO~O]mOi!TX!s!TXT!TX~OioO!s!PXT!PX~ObRO!soXToX~OVTOirOnsO~O[VOivO~OWXOizO~OXZOi}O~OY]Oi!QO~OZ`Oi!TO!svXTvX~O^bOioO~O`dOioO~OSfOi!]O~O!s!`O~P]O!s!eO~OP!jO]mOivO~OQ!lOi!YXn!YX!s!YXT!YX~OirOnsO!spaTpa~OQ!lOi!TX!s!TX!o!TX!p!TX!q!TX!r!TXT!TX~OioO!sqaTqa~OQ!lO!ssaTsa~OQ!lO!staTta~OQ!lO!suaTua~OQ!lO!svaTva~Oa!oOioO~O_!qOioO~O]mOc!tOd!vO~OVTOWXOXZOY]OZ`O[VO^bO`dObROiPO!s!`O~OioO!o!|O!p!|O!q!|O!r!|O!shiThi~OP!jOirOnsO~OQ!lOR#SOi#UO~Oa!oOi#WO~O_!qOi#YO~OU#ZO]mOi#]On#]O~Oc!tOi#_O~Od!vOi#aO~OThO!syi~O!o!|O!p!|O!q!|O!r!|O!skqTkq~OirOnsO!smqTmq~OR#SOijinji!sjiTji~OU#ZOV{iW{iX{iY{iZ{i[{i^{i`{ib{ii{i!s{i~OThO!syq~OioO!o!Wa!p!Wa!q!Wa!r!Wa!s!WaT!Wa~O",
  goto: ")n!lPPPPPPPPPPPPPPPPPPPPPPP!m!qP!{!q#e!qP!q!q!q!q#i#i#i!q!q!q#q#u#x#x#x#{!q$X$c$i$s%d%o%u%{&R&]&h&s'O'Z'f'q'|(X(_(j(p(w(})T)Z)eTkOlSjOlX!bi!_!a!xWsUt!k#QQyWQ|YQ!P[Q!S^Q!VaR!inT!}!h#O]_Oil!_!a!xTjOlR!_gR!^gQ!diQ!y!_Q!{!aR#b!xSjOlQ#c!yR#h#bQlOR!flQnPS!gn!sR!s!][QOil!_!a!x[pQw!W!Y!h#dQwWQ!WcQ!YeQ!hnR#d!}[!mrvz}!Q!TR#R!mQ#T!mR#f#TQ#O!hR#e#OQ!knR#P!kQtUS!nt#QR#Q!k[SOil!_!a!xRqS[UOil!_!a!xRuU[WOil!_!a!xRxW[YOil!_!a!xR{Y[[Oil!_!a!xR!O[[^Oil!_!a!xR!R^[aOil!_!a!xR!Ua[cOil!_!a!xR!XcQ!p!WR#V!p[eOil!_!a!xR!ZeQ!r!YR#X!rSgOlR![gQ#[!sR#g#[Q!u!]R#^!uQ!w!]R#`!wQ!aiQ!x!_T!z!a!xWiOl!y#bR!ci",
  nodeNames: "⚠ ask at random if else pressed print forward turn color sleep play is add from remove to_list clear in not_in Comment Program Command Assign Text ListAccess AssignList Op Ask String Clear Print Play Turtle Forward Turn Color Sleep Add Remove If Condition EqualityCheck InListCheck NotInListCheck IfLessCommand ErrorInvalid Else",
  maxTerm: 81,
  nodeProps: [
    ["group", 34,"turtle"]
  ],
  skippedNodes: [0,21],
  repeatNodeCount: 25,
  tokenData: "'t~RcYZ!^pq!crs!hst$[tu$swx%q|}'`!c!}$s#R#S$s#T#o$s$gBn$sBnBo'eBo&FV$s&FV&FW'j&FW;'S$s;'S;=`%k<%l?Hb$s?Hb?Hc'o?HcO$s~!cO!s~~!hO!n~~!kWOY!hZr!hrs#Ts#O!h#O#P#Y#P;'S!h;'S;=`$U<%lO!h~#YOn~~#]RO;'S!h;'S;=`#f;=`O!h~#iXOY!hZr!hrs#Ts#O!h#O#P#Y#P;'S!h;'S;=`$U;=`<%l!h<%lO!h~$XP;=`<%l!h~$aSe~OY$[Z;'S$[;'S;=`$m<%lO$[~$pP;=`<%l$[~$xZi~tu$s!Q![$s!c!}$s#R#S$s#T#o$s$gBn$sBo&FV$s&FW;'S$s;'S;=`%k<%l?Hb$s?HcO$s~%nP;=`<%l$s~%tWOY%qZw%qwx#Tx#O%q#O#P&^#P;'S%q;'S;=`'Y<%lO%q~&aRO;'S%q;'S;=`&j;=`O%q~&mXOY%qZw%qwx#Tx#O%q#O#P&^#P;'S%q;'S;=`'Y;=`<%l%q<%lO%q~']P;=`<%l%q~'eO!o~~'jO!p~~'oO!r~~'tO!q~",
  tokenizers: [0],
  topRules: {"Program":[0,22]},
  dynamicPrecedences: {"47":-10},
  specialized: [{term: 25, get: (value: any, stack: any) => (specializeKeyword(value, stack) << 1), external: specializeKeyword},{term: 25, get: (value: any, stack: any) => (extendKeyword(value, stack) << 1) | 1, external: extendKeyword, extend: true}],
  tokenPrec: 0
})
