// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeKeyword, extendKeyword} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",`QYQPOOOOQO'#DR'#DRQYQPOOO}QPO'#DUO!]QPO'#DQOOQO'#D['#D[O!hQPO'#CvOOQO'#D]'#D]O!sQPO'#CwOOQO'#D^'#D^O#OQPO'#CxOOQO'#D_'#D_O#WQPO'#CzOOQO'#D`'#D`O#`QPO'#C{OOQO'#Da'#DaO#hQPO'#C|OOQO'#Cy'#CyOOQO'#Db'#DbO#pQPO'#C}OOQO'#Dc'#DcO$OQPO'#DOOOQO'#De'#DeO$WQPO'#DPOOQO'#Cn'#CnQxQPO'#DSQ$`QPOOOOQO-E7P-E7POOQO'#DT'#DTO%QQPO,59ZOOQO'#DU'#DUOOQO-E7S-E7SOOQO-E7Y-E7YO%]QPO'#DZOOQO'#DZ'#DZO%nQPO,59cOOQO-E7Z-E7ZO%|QPO'#DUO&hQPO,59dOOQO-E7[-E7[OOQO,59d,59dO&sQPO,59fOOQO-E7]-E7]OOQO,59f,59fO'OQPO,59gOOQO-E7^-E7^OOQO,59g,59gO'ZQPO,59hOOQO-E7_-E7_OOQO,59h,59hO'fQPO,59iOOQO-E7`-E7`OOQO,59i,59iO'qQPO,59jOOQO-E7a-E7aO'yQPO,59kOOQO-E7c-E7cO(RQPO,59nOOQO-E7Q-E7QOOQO-E7R-E7RO(yQPO1G.uOOQO1G.u1G.uOOQO'#DY'#DYO)bQPO1G.zOOQO'#DV'#DVO)mQPO,59]OOQO-E7X-E7XOOQO'#Dd'#DdO)xQPO1G/UOOQO'#Df'#DfO*QQPO1G/VOOQO'#Cs'#CsO$RQPO'#DXO*YQPO7+$dOOQO-E7W-E7WO*nQPO7+$fOOQO-E7T-E7TOOQO'#DW'#DWO*|QPO1G.wOOQO1G.w1G.wOOQO-E7b-E7bOOQO7+$p7+$pOOQO-E7d-E7dOOQO7+$q7+$qO+_QPO,59sOOQO-E7V-E7VOOQO-E7U-E7U",
  stateData: "+v~O!]OS`OS~OSVOTZOU]OV_OWbOXXOZdO]fO_TOdRO!^PO~OYlOdxX!ZxX!^xX~OdnO!ZtX!^tX~O_TO!ZjX!^jX~OSVOdqOirO~OXXOduO~OTZOdyO~OU]Od|O~OV_Od!PO~OWbOd!SO!ZqX!^qX~OZdOdnO~O]fOdnO~OSVOTZOU]OV_OWbOXXOZdO]fO_TOdRO~OP!`OYlOduO~OQ!bOd}Xi}X!Z}X!^}X~OdqOirO!Zka!^ka~OQ!bOdxX!ZxX!^xX!_xX!`xX!axX!bxX~OdnO!Zla!^la~OQ!bO!Zna!^na~OQ!bO!Zoa!^oa~OQ!bO!Zpa!^pa~OQ!bO!Zqa!^qa~O^!eOdnO~O[!gOdnO~O!^POSvaTvaUvaVvaWvaXvaZva]va_vadva!Zva~OdnO!_!iO!`!iO!a!iO!b!iO!Zci!^ci~OP!`OdqOirO~OQ!bOR!oOd!qO~O^!eOd!sO~O[!gOd!uO~O!_!iO!`!iO!a!iO!b!iO!Zfq!^fq~OdqOirO!Zhq!^hq~OR!oOdeiiei!Zei!^ei~OdnO!Z{a!^{a!_{a!`{a!a{a!b{a~O",
  goto: "&}!ZPPPPPPPPPPPPPPPPPP![!aP!f!a#O!aP!a!a!a!a#S#S#S!a!a!a!a#X#c#j#p$^$i$o$u${%V%_%g%o%w&P&X&a&i&o&wViOQjVhOQjWrWs!a!mQxYQ{[Q!O^Q!R`Q!UcR!_mT!j!^!kVaOQjQQOSkQ!ZR!ZiSjOQR![jQmRR!]mUSOQj[oSv!V!X!^!vQvYQ!VeQ!XgQ!^mR!v!j[!cquy|!P!SR!n!cQ!p!cR!x!pQ!k!^R!w!kQ!amR!l!aQsWS!ds!mR!m!aUUOQjRpUUWOQjRtWUYOQjRwYU[OQjRz[U^OQjR}^U`OQjR!Q`UcOQjR!TcUeOQjR!WeQ!f!VR!r!fUgOQjR!YgQ!h!XR!t!h",
  nodeNames: "⚠ ask at random print forward turn color sleep play is add from remove to_list clear Comment Program Command Assign Text ListAccess AssignList Op Ask String Clear Print Play Turtle Forward Turn Color Sleep Add Remove ErrorInvalid",
  maxTerm: 64,
  nodeProps: [
    ["group", 29,"turtle"]
  ],
  skippedNodes: [0,16],
  repeatNodeCount: 20,
  tokenData: ")V~R}YZ$Opq$Tqr$Yrs&ust'jtu$Yuv$Yvw$Ywx(Rxy$Yyz$Yz{$Y{|$Y|}(q}!O$Y!O!P$Y!P!Q$Y!Q![$Y![!]$Y!]!^$Y!^!_$Y!_!`$Y!`!a$Y!a!b$Y!b!c$Y!c!}$Y!}#O$Y#O#P$Y#P#Q$Y#Q#R$Y#R#S$Y#S#T$Y#T#o$Y#o#p$Y#q#r$Y#r#s$Y$gBn$YBnBo(vBo&FV$Y&FV&FW({&FW;'S$Y;'S;=`&o<%l?Hb$Y?Hb?Hc)Q?HcO$Y~$TO!^~~$YO!]~~$_td~qr$Ytu$Yuv$Yvw$Yxy$Yyz$Yz{$Y{|$Y}!O$Y!O!P$Y!P!Q$Y!Q![$Y![!]$Y!]!^$Y!^!_$Y!_!`$Y!`!a$Y!a!b$Y!b!c$Y!c!}$Y!}#O$Y#O#P$Y#P#Q$Y#Q#R$Y#R#S$Y#S#T$Y#T#o$Y#o#p$Y#q#r$Y#r#s$Y$gBn$YBo&FV$Y&FW;'S$Y;'S;=`&o<%l?Hb$Y?HcO$Y~&rP;=`<%l$Y~&xVOY&uZr&urs'_s#O&u#P;'S&u;'S;=`'d<%lO&u~'dOi~~'gP;=`<%l&u~'oS`~OY'jZ;'S'j;'S;=`'{<%lO'j~(OP;=`<%l'j~(UVOY(RZw(Rwx'_x#O(R#P;'S(R;'S;=`(k<%lO(R~(nP;=`<%l(R~(vO!_~~({O!`~~)QO!b~~)VO!a~",
  tokenizers: [0],
  topRules: {"Program":[0,17]},
  dynamicPrecedences: {"36":-10},
  specialized: [{term: 20, get: (value: any, stack: any) => (specializeKeyword(value, stack) << 1), external: specializeKeyword},{term: 20, get: (value: any, stack: any) => (extendKeyword(value, stack) << 1) | 1, external: extendKeyword, extend: true}],
  tokenPrec: 0
})
