// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_TextWithoutSpaces = {__proto__:null,print:12, ask:18, echo:22, forward:28, turn:32, left:34, right:36, color:40}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lOYQPOOOOQO'#Ch'#ChOqQPO'#CqOOQO'#C_'#C_OOQO'#Cr'#CrQYQPOOO!`QPO'#C`O!eQPO'#CdO!jQPO'#CfO!oQPO'#CiO!tQPO'#CkO!|QPO'#CoOOQO,59],59]OOQO-E6p-E6pOOQO,58z,58zOOQO,59O,59OOOQO,59Q,59QOOQO,59T,59TOOQO,59V,59VOOQO,59Z,59Z",
  stateData: "#U~OPOSiOS~OTQOUUOXVOZWO^XO`YOdZO~OV[OTeXUeXXeXZeX^eX`eXdeXgeX~OV^O~OV_O~OV`O~OVaO~OabObbO~OVcO~OTV~",
  goto: "zgPPPhlPPPlPlPlpPpPPPpPltTSOTTROTTPOTQTOR]T",
  nodeNames: "⚠ Comment Program Command Print TextWithoutSpaces print Text Ask ask Echo echo Turtle Forward forward Turn turn left right Color color ErrorInvalid",
  maxTerm: 25,
  nodeProps: [
    ["group", 12,"turtle"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "$n~R]OYzYZ$QZ]z]^!n^pzpq#]qszst$VtCtzCtCu!nCu;'Sz;'S;=`#z<%lOz~!RXT~V~OYzZ]z]^!n^pzpq#]qszt;'Sz;'S;=`#z<%lOz~!sUT~OY!nZp!nqs!nt;'S!n;'S;=`#V<%lO!n~#YP;=`<%l!n~#bUV~OY#]Z]#]^s#]t;'S#];'S;=`#t<%lO#]~#wP;=`<%l#]~#}P;=`<%lz~$VOi~~$[SP~OY$VZ;'S$V;'S;=`$h<%lO$V~$kP;=`<%l$V",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 5, get: (value) => spec_TextWithoutSpaces[value] || -1}],
  tokenPrec: 95
})
