// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Command = 3,
  Print = 4,
  TextWithoutSpaces = 5,
  Text = 7,
  Ask = 8,
  Echo = 10,
  Turtle = 12,
  Forward = 13,
  Turn = 15,
  Color = 19,
  ErrorInvalid = 21
