//Generated through generate-syntax-keywords
export const LANG_fr = {
'_PRINT':'(?:affiche|print)',
'_ASK':'(?:demande|ask)',
'_ECHO':'(?:dit|echo)',
'_FORWARD':'(?:avance|forward)',
'_TURN':'(?:tourne|turn)',
'_COLOR':'(?:color|color)',
'_BLACK':'(?:black|black)',
'_BLUE':'(?:blue|blue)',
'_BROWN':'(?:brown|brown)',
'_GRAY':'(?:gray|gray)',
'_GREEN':'(?:green|green)',
'_ORANGE':'(?:orange|orange)',
'_PINK':'(?:pink|pink)',
'_PURPLE':'(?:purple|purple)',
'_RED':'(?:red|red)',
'_WHITE':'(?:white|white)',
'_YELLOW':'(?:yellow|yellow)',
'_LEFT':'(?:gauche|left)',
'_RIGHT':'(?:droite|right)',
'_IS':'(?:est|is)',
'_SLEEP':'(?:dors|sleep)',
'_ADD_LIST':'(?:ajoute|add)',
'_TO_LIST':'(?:à|a|to)',
'_REMOVE':'(?:supprime|remove)',
'_FROM':'(?:de|from)',
'_AT':'(?:au|at)',
'_RANDOM':'(?:hasard|random)',
'_IN':'(?:dans|in)',
'_IF':'(?:si|if)',
'_ELSE':'(?:sinon|else)',
'_AND':'(?:et|and)',
'_REPEAT':'(?:répète|repete|repeat)',
'_TIMES':'(?:fois|times)',
'_FOR':'(?:pour|for)',
'_RANGE':'(?:intervalle|range)',
'_TO':'(?:à|a|to)',
'_STEP':'(?:pas|step)',
'_ELIF':'(?:sinon si|elif)',
'_INPUT':'(?:saisie|input)',
'_OR':'(?:ou|or)',
'_WHILE':'(?:tant que|while)',
'_LENGTH':'(?:longueur|length)',
}
