//Generated through generate-syntax-keywords
export const LANG_nl = {
'_PRINT':'(?:print|print)',
'_ASK':'(?:vraag|ask)',
'_ECHO':'(?:echo|echo)',
'_FORWARD':'(?:vooruit|forward)',
'_TURN':'(?:draai|turn)',
'_COLOR':'(?:color|color)',
'_RED':'(?:red|red)',
'_BLUE':'(?:blue|blue)',
'_LEFT':'(?:links|left)',
'_RIGHT':'(?:rechts|right)',
'_IS':'(?:is|is)',
'_SLEEP':'(?:slaap|sleep)',
'_ADD_LIST':'(?:voeg|add)',
'_TO_LIST':'(?:toe aan|to)',
'_REMOVE':'(?:verwijder|remove)',
'_FROM':'(?:uit|from)',
'_AT':'(?:op|at)',
'_RANDOM':'(?:willekeurig|random)',
'_IN':'(?:in|in)',
'_IF':'(?:als|if)',
'_ELSE':'(?:anders|else)',
'_AND':'(?:en|and)',
'_REPEAT':'(?:herhaal|repeat)',
'_TIMES':'(?:keer|times)',
'_FOR':'(?:voor|for)',
'_RANGE':'(?:bereik|range)',
'_TO':'(?:tot|to)',
'_STEP':'(?:stap|step)',
'_ELIF':'(?:alsanders|elif)',
'_INPUT':'(?:invoer|input)',
'_OR':'(?:of|or)',
'_WHILE':'(?:zolang|while)',
'_LENGTH':'(?:lengte|length)',
}
