//Generated through generate-syntax-keywords
export const LANG_hi = {
'_PRINT':'(?:print|प्रिंट)',
'_ASK':'(?:ask|पूछें)',
'_ECHO':'(?:echo|गूंज)',
'_FORWARD':'(?:forward|आगे)',
'_TURN':'(?:|मोड़)',
'_LEFT':'left',
'_RIGHT':'right',
'_IS':'(?:is|है)',
'_SLEEP':'(?:sleep|नींद)',
'_ADD_LIST':'(?:add|जोड़ना)',
'_TO_LIST':'(?:to|से)',
'_REMOVE':'(?:remove|हटाना)',
'_FROM':'(?:from|से)',
'_AT':'(?:at|पर)',
'_RANDOM':'(?:random|अनियमित)',
'_IN':'(?:in|में)',
'_IF':'(?:if|अगर)',
'_ELSE':'(?:else|अन्यथा)',
'_AND':'(?:and|और)',
'_REPEAT':'(?:repeat|दोहराना)',
'_TIMES':'(?:times|बार)',
'_FOR':'(?:for|के लिये)',
'_RANGE':'(?:range|श्रेणी)',
'_TO':'(?:to|से)',
'_STEP':'(?:step|क़दम)',
'_ELIF':'(?:elif|एलिफ)',
'_INPUT':'(?:input|इनपुट)',
'_OR':'(?:or|या)',
'_WHILE':'(?:while|व्हाइलw)',
'_LENGTH':'(?:length|लंबाई)',
}
