//Generated through generate-syntax-keywords
export const LANG_tr = {
'_PRINT':'(?:yazdır|print)',
'_ASK':'(?:sor|ask)',
'_ECHO':'(?:eko|echo)',
'_FORWARD':'(?:ileri|forward)',
'_TURN':'(?:döndür|turn)',
'_COLOR':'(?:color|color)',
'_LEFT':'(?:sol|left)',
'_RIGHT':'(?:sağ|right)',
'_IS':'(?:eşit|is)',
'_SLEEP':'(?:bekle|sleep)',
'_ADD_LIST':'(?:ekle|add)',
'_TO_LIST':'(?:to|to)',
'_REMOVE':'(?:sil|remove)',
'_FROM':'(?:şuradan|from)',
'_AT':'(?:şurada|at)',
'_RANDOM':'(?:rastgele|random)',
'_IN':'(?:içinde|in)',
'_IF':'(?:eğer|if)',
'_ELSE':'(?:başka|else)',
'_AND':'(?:ve|and)',
'_REPEAT':'(?:tekrar|repeat)',
'_TIMES':'(?:kere|times)',
'_FOR':'(?:şunun için|for)',
'_RANGE':'(?:dizi|range)',
'_TO':'(?:şuraya|to)',
'_STEP':'(?:adım|step)',
'_ELIF':'(?:elif|elif)',
'_INPUT':'(?:girdi|input)',
'_OR':'(?:veya|or)',
'_WHILE':'(?:iken|while)',
'_LENGTH':'(?:uzunluk|length)',
}