import os
from workbook_rewriter import process_workbook

current_directory = os.path.dirname(os.path.abspath(__file__))

min_lesson = 5
max_lesson = 6

for lesson in range(min_lesson, max_lesson):
    json_data = process_workbook(lesson, current_directory)
    print()

    output_path = f"/lesson{lesson}/les{lesson}a-autogenerated.md"

    f = open(current_directory+output_path, "w")
    f.write(json_data)
    f.close()
