#!/bin/bash
set -eu

# Generate the lezer parsers from the grammars specified in  highlighting/lezer-grammars/
for grammarFile in ../../highlighting/lezer-grammars/level*.grammar ; do
    baseName=$(basename "$grammarFile")
    tsFile=${baseName%.grammar}-parser.ts
    npx lezer-generator --typeScript "$grammarFile" -o ../../static/js/lezer-parsers/$tsFile
done