#!/bin/bash
set -eu

# Generate the lezer parsers from the grammars specified in  highlighting/lezer-grammars/
for level in $(seq 1 18);
do
    npx lezer-generator --typeScript  ../../highlighting/lezer-grammars/level${level}.grammar -o ../../static/js/lezer-parsers/level${level}-parser.ts
done