#!/bin/bash
set -eu
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir

echo "------> Validating YAML"

# Validate adventure files against their schema
#
# The error messages produced by pajv are pretty bad, but we will just
# say that getting an error is better than getting NO error.
#
# If we ever care enough to do something about this, we should be interpreting
# the JSON error outputs of this tool and re-interpreting them with useful
# error messages.


# For magical and mysterious reasons, on GitHub actions using 'npx pajv validate' (which
# would normally be the way to run this command), hangs. It works fine on two of my machines,
# and also in an Ubuntu Docker container, and 'npx pajv help' works as well... but
# 'npx pajv validate' just hangs. Running the 'pajv' binary directly without the use of
# 'npx' does work... so we're just going to ¯\_(ツ)_/¯ and do that.

pajv=$scriptdir/../../node_modules/.bin/pajv

echo "------> Validating adventures"
cd ../../content/adventures/
$pajv validate \
    --errors=text \
    -s "adventures.schema.json" \
    -d "*.yaml"
echo "------> Adventure yaml files are valid"

echo "------> Validating level defaults"
cd ../level-defaults/
$pajv validate \
    --errors=text \
    -s "levels.schema.json" \
    -d "*.yaml"
echo "------> Level default yaml files are valid"

#echo "------> Validating level commands"
#cd ../commands/
#$pajv validate \
#    --errors=text \
#    -s "commands.schema.json" \
#    -d "*.yaml"
#echo "------> Commands yaml files are valid"

echo "------> Validating quizzes"
cd ../quizzes/
$pajv validate \
    --errors=text \
    -s "quizzes.schema.json" \
    -d "*.yaml"
echo "------> Quiz yaml files are valid"


# Validate-texts is producing a lot of noise and it will never fail the build outright
# anyway (if it would, pajv would have complained earlier), so might as well disable it for now.
# node $scriptdir/validate-texts.js $scriptdir
