#!/usr/bin/env python3
# Check all .po files, and make sure they don't have duplicate msgid's in there.
# (Perhaps normal and commented out).
#
# As well as checking for files that have been wrapped, which they shouldn't be.
# Our extraction scripts make sure the files are extracted unwrapped, and we
# *should have configured* Weblate to do the same, but sometimes Weblate still wraps.
from os import path
import collections
import os
import re
import sys


def scan_pofiles(root, scanner):
    """Return True if there are any problems."""
    ret = False
    for dir, _, files in os.walk(root):
        for file in files:
            if file.endswith('.po'):
                fullpath = path.join(dir, file)
                ret |= scanner(fullpath)
    return ret


PAT = re.compile('^(?:#~ )?msgid "(.*)"')


def check_for_duplicates(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()

    indexes = collections.defaultdict(list)
    for i, line in enumerate(lines):
        m = PAT.match(line)
        if m:
            indexes[m.group(1)].append(i)

    morethanonce = [(word, lines) for word, lines in indexes.items() if len(lines) > 1]
    if len(morethanonce) == 0:
        return False

    print('-' * 70)
    print(filename)
    print('-' * 70)

    for word, linenrs in morethanonce:
        print(f"The translation of '{word}' occurs {len(linenrs)} times:")
        print('')
        for nr in linenrs:
            print(f'    {nr + 1}: {lines[nr]}')
            print(f'    {nr + 2}: {lines[nr + 1]}')
            print('')

    return True


def check_for_wrapping(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()

    failed = False

    # Check for `msgstr ""`, which a wrapped entry always starts with.
    # The first 20 or so lines are the header which always contain a `msgstr ""`. Skip those.
    for nr, line in enumerate(lines):
        if nr < 20:
            continue

        if 'msgstr ""' in line:
            print(f'{path.relpath(filename)}:{nr + 1}: msgstr has been wrapped!')
            failed = True

    return failed


if __name__ == '__main__':
    pofilespath = path.join(path.dirname(__file__), '..', '..', 'translations')
    fail = False
    fail |= scan_pofiles(pofilespath, check_for_duplicates)
    fail |= scan_pofiles(pofilespath, check_for_wrapping)
    if fail:
        print('Something went wrong with the gettext translation files.')
        print('See above for the problems.')
        print('')
        print('- If duplicates were found, please make sure every msgid occurs only once,')
        print('  not commented out, with the right translation.')
        print('- If lines were wrapped, run the extraction script again to remove wrapping')
        print('  and double-check the Weblate configuration.')
        sys.exit(1)
