#!/bin/bash
# Run pylint against all Python code

# TODO - JW 2023-10-03 for PR #4574
# Do we still need this with flake8 in place?

set -eu
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir/../..

echo "------> Linting Python code"

# There are MANY pep8 style violations in the code base currently.
# Let's just check for definite errors.
pylint -j 0 \
    --errors-only \
    *.py website highlighting tests
