#!/bin/bash
# Helper script to run e2e tests against a local test instance
set -eu
scriptdir=$(cd $(dirname $0) && pwd)

echo "------> End-to-end tests"

# This is expected to run from the repo root
cd $scriptdir/../..

pids=""
trap 'kill $pids' EXIT

export PORT=5050
env HEROKU_APP_NAME=localhost BASE_URL=http://localhost:$PORT SECRET_KEY=TheSecret python app.py > e2e-server.log 2>&1 &
pids="$pids $!"

endpoint=http://localhost:$PORT

# We need to wait a bit for the server to come up. curl for a max time
echo "Waiting for server to start..." >&2
up=false
for i in $(seq 0 3000); do
    if curl -sSf "$endpoint" > /dev/null 2>&1; then
        up=true
		break
	fi
done

if ! $up; then
  echo "Server didn't start in time..." >&2
  echo "Here's what it had to say:" >&2
  echo "-------------------------------------------" >&2
  cat e2e-server.log >&2
  echo "-------------------------------------------" >&2
  exit 1
fi

# Finally!
if ! env ENDPOINT=http://localhost:$PORT pytest -q tests_e2e.py "$@"; then
    # Sleep a bit to give the server the chance to flush the log
    echo "Some e2e test failed. Here's the tail of the server log:" >&2
    tail -n 50 e2e-server.log >&2
    exit 1
fi
