#!/bin/bash
# Run all validation scripts.
# This script runs on GitHub in the PR build, NOT ON HEROKU. It can therefore not
# rely on the dependencies of the top-level package.json having been installed.
set -eu
scriptdir=$(cd $(dirname $0) && pwd)

$scriptdir/validate-python
$scriptdir/validate-typescript
$scriptdir/validate-yaml
if [[ "${1:-}" == "--all" ]]; then
  $scriptdir/validate-tests --all
elif [[ "${1:-}" == "--weblate" ]]; then
  $scriptdir/validate-tests --weblate
else
  $scriptdir/validate-tests
fi
$scriptdir/validate-e2e
python3 $scriptdir/validate-pofiles

echo "Everything is great! 🍰"
