#!/bin/bash
set -eu
set -x
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir

echo "------> Validating YAML"

# Validate adventure files against their schema
#
# The error messages produced by pajv are pretty bad, but we will just
# say that getting an error is better than getting NO error.
#
# If we ever care enough to do something about this, we should be interpreting
# the JSON error outputs of this tool and re-interpreting them with useful
# error messages.
which npx
npx pajv help


cd ../../coursedata/adventures/
$scriptdir/../../node_modules/.bin/pajv validate \
    --errors=text \
    -s "adventures.schema.json" \
    -d "*.yaml"

cd ../level-defaults/
npx pajv validate \
    --errors=text \
    -s "levels.schema.json" \
    -d "*.yaml"

cd ../quiz/
npx pajv validate \
    --errors=text \
    -s "quiz_questions.schema.json" \
    -d "*.yaml"

node $scriptdir/validate-texts.js $scriptdir
