#!/bin/bash
# Helper script to run unit tests
set -eu
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir/../..

echo "------> Python unit tests"

# This is expected to run from the repo root
python -m pytest
