name: Build offline Hedy
on:
  # Can be run on-demand
  workflow_dispatch: {}

  # Runs when 'deploy to prod' runs
  workflow_run:
    workflows: ["Deploy to hedy.org"]
    types: [requested]
    branches:
      - 'main'


jobs:
  setup_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.daily-version.outputs.version }}
      created: ${{ steps.daily-version.outputs.created }}
    steps:
      - uses: actions/checkout@v6

      - uses: fregante/daily-version-action@v2
        name: Create tag if necessary
        id: daily-version


  build_ubuntu:
    runs-on: ubuntu-latest
    needs: setup_release
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: pip install -r requirements.txt
      name: 'Python requirements'
    - run: doit run _offline
    - name: Smoke test the build
      run: cd dist && offlinehedy/run-hedy-server --smoketest

    - name: Install zip
      run: sudo apt-get install zip
    - name: Create zip file
      run: |
        cd dist/offlinehedy && zip -r ../../offlinehedy-${{ needs.setup_release.outputs.version }}-ubuntu.zip .

    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu_build
        path: ../../offlinehedy-${{ needs.setup_release.outputs.version }}-ubuntu.zip


  build_windows:
    runs-on: windows-latest
    needs: setup_release
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: 'Install npx'
      run: npm install -g npx
    - run: pip install -r requirements.txt
      name: 'Python requirements'
    - run: doit run _offline
    - name: Smoke test the build
      run: cd dist && offlinehedy/run-hedy-server --smoketest

    - name: Create zip file
      # Because we're on Windows
      run: |
        cd dist/offlinehedy &&  Compress-Archive -Path . -Destination ../../offlinehedy-${{ needs.setup_release.outputs.version }}-windows.zip


    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows_build
        path: ../../offlinehedy-${{ needs.setup_release.outputs.version }}-windows.zip


  deploy_release:
    runs-on: ubuntu-latest
    needs: [setup_release, build_ubuntu, build_windows]
    steps:
    - if: needs.setup_release.outputs.created
      name: Create Release
      uses: shogo82148/actions-create-release@v1
      id: create_release
      with:
        tag_name: ${{ needs.setup_release.outputs.version }}
        generate_release_notes: true


    - name: Download ubuntu build
      uses: actions/download-artifact@v5
      with:
        name: ubuntu_build

    - name: Download math result for job 1
      uses: actions/download-artifact@v5
      with:
        name: windows_build


    - name: Upload Assets
      if: needs.setup_release.outputs.created
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.setup_release.outputs.version }}
        working_directory: .
        files: |
          *.zip
