name: Build offline Hedy Macos
on:
  # Can be run on-demand
  workflow_dispatch: {}

  # Runs when 'deploy to prod' runs
  workflow_run:
    workflows: ["Deploy to hedy.org"]
    types: [requested]
    branches:
      - 'main'


jobs:

  build_macos_silicon:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - uses: fregante/daily-version-action@v2
      name: Create tag if necessary
      id: daily-version
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: pip install -r requirements.txt
      name: 'Python requirements'
    - run: doit run _offline_macos
    - name: Smoke test the build
      run: cd dist && offlinehedy/run-hedy-server --smoketest

    - name: Create zip file
      run: |
        cd dist/offlinehedy && zip -r ../../offlinehedy-${{ steps.daily-version.outputs.version }}-macos-silicon.zip .

    - if: steps.daily-version.outputs.created
      name: Create release
      uses: shogo82148/actions-create-release@v1
      id: create_release
      with:
        tag_name: ${{ steps.daily-version.outputs.version }}
        generate_release_notes: true

    - name: Upload assets
      if: steps.daily-version.outputs.created
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.daily-version.outputs.version }}
        working_directory: .
        files: |
          *.zip
